name: Keep GitHub Active

on:
  schedule:
    - cron: "*/1 * * * *" # Jalan setiap 1 menit
  workflow_dispatch: # Bisa dijalankan manual

jobs:
  keep-active:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Commit and push
        run: |
          git config --global user.name "XenaaLangliss"
          git config --global user.email "myxena.mail@gmail.com"
          git commit --allow-empty -m "Keep GitHub Active"
          git push
